### ISSUE TITLE
Are we trying to revive it?

### ISSUE THREAD

**Issue by Shiny-andKittens** [DragonetMC/DragonProxy#1]
If so, we need people to come back to this.

@DefinitelyEvil especially

**Comment by Shiny-andKittens** [comment]
@TheDiamondYT1 @DefinitelyEvil 
I want to ask, how was it originally coded? Or how it was intended before it became worthlessly tangled?

**Comment by Pet0203** [comment]
I can't do much until chunk rendering is fixed, but I'll be here watching ;)

**Comment by DefinitlyEvil** [comment]
To fix chunks, just debugging and again debugging, nothing fancy but pain in the ass.

**Comment by RednedEpic** [comment]
I would be happy to help revive this project. I understand it has been done before but I have a few friends that may be interested in helping if needed.

**Comment by TheDiamondYT1** [comment]
@RednedEpic Adding you to the organization, please accept invitation

**Comment by TekkitCommando** [comment]
@TheDiamondYT1 why do you add people to the org immediately, please start having then send a few PR's before inviting them to the org. You adding everyone has caused some people to start trolling and changing issue comments.

**Comment by RednedEpic** [comment]
If you don't trust me yet, feel free to remove me. I totally understand what you mean. If you need me to do anything just let me know.

**Comment by TekkitCommando** [comment]
@RednedEpic you were already added it would be unfair. It is fine this time.

**Comment by RednedEpic** [comment]
Alright, what should we start on?

**Comment by TekkitCommando** [comment]
The others seemed to agree on chunk loading issues.

**Comment by TheDiamondYT1** [comment]
Well if you look at the repo its completely empty

**Comment by RednedEpic** [comment]
Yes I understand, I hope you don't mind, I will get started with the core part of Proxy (e.g: Protocol Numbers etc.)

**Comment by TheDiamondYT1** [comment]
@RednedEpic Okay. Keep in mind the current MCPE protocol is a dick to work with

**Comment by TekkitCommando** [comment]
I worked on the server software itself and not a proxy so I am not sure the exact differences but I guess just try to start on working on the protocol and making the handshake connection and then serializable messages (the motd, etc.) Do you have any other suggestions @TheDiamondYT1

**Comment by RednedEpic** [comment]
Alrighty

**Comment by TekkitCommando** [comment]
@TheDiamondYT1 do you agree with my suggestion or do you think he should go with something different?

**Comment by TekkitCommando** [comment]
@TheDiamondYT1 do you agree with my suggestion or do you think he should go with something different?

**Comment by TheDiamondYT1** [comment]
@TekkitCommando @RednedEpic Use https://github.com/JRakNet/JRakNet. Look in the [Dragonet](https://github.com/DragonetMC/Dragonet) repo in pom.xml for the maven repo. 

Don't use maven modules. Thats how i messes it up in the first place.

Check out [voxelwind](https://github.com/voxelwind/voxelwind).

**Comment by TheDiamondYT1** [comment]
And yes, work on the protocol

**Comment by RednedEpic** [comment]
I will get started on the main parts like storing protocol information and packet IDS.

**Comment by RednedEpic** [comment]
Since 1.12 is a fairly new release, lets stick with supporting Minecraft 1.11.2 servers for the time being. Unless we code this to support all versions of Minecraft like 1.8 or 1.9 and up.

**Comment by TheDiamondYT1** [comment]
Start with 1.11.2 and backport it later

**Comment by RednedEpic** [comment]
okay

**Comment by RednedEpic** [comment]
Completed Minecraft PE Protocol ID list.

**Comment by TheDiamondYT1** [comment]
@RednedEpic Push it

**Comment by BrettplayMC** [comment]
This is a very interesting project.  So this will all PE clients on PC or vice versa?

**Comment by Shiny-andKittens** [comment]
@thediamondYT1 have you heard of how they're merging all mobile and console versions?

**Comment by TheDiamondYT1** [comment]
@Shiny-andKittens The "Better Together Update". Yes, i'm aware.

**Comment by filfat** [comment]
I have quite a good base to expand on over at https://github.com/filfat/Node-MineiaGo if you're sufficient in JavaScript. Currently I need to get around to updating the bedrock protocol.

**Comment by RednedEpic** [comment]
Sorry for the late response, I have been extremely busy the past few days but I am back now.

@filfat that seems cool! Sadly I know almost no JavaScript so I can't help you there :(.

@TheDiamondYT1 I don't have permission to upload anything for some reason. I have the packet class complete, and starting on other things now. Mostly just utility classes for now. Let me know when you have time to help me out. Thanks.

**Comment by Shiny-andKittens** [comment]
@RednedEpic I think @TheDiamondYT1 meant to make a Pull Request for it, so he can view the changes himself

**Comment by TheDiamondYT1** [comment]
I don't really care right now.

**Comment by Shiny-andKittens** [comment]
Ok, so I want to ask, what needs done first? I'm thinking rebuilding to code to convert PE --> PC packets

**Comment by TheDiamondYT1** [comment]
I could probably do it... I might try after

**Comment by Shiny-andKittens** [comment]
I think that this time, we need to add some organization to this repo, to make sure that it doesn't happen again

**Comment by RednedEpic** [comment]
I made a pull request and realized that the file wasn't a java file. I fixed the error and it show be okay.

**Comment by RednedEpic** [comment]
It seems @kingcraftingnl forked the project and updated it to work with MCPE 1.0.9. Maybe we could get him to help us out with this.

**Comment by Shiny-andKittens** [comment]
I think we should try to get ahold of people like @thebigsmileXD , @DaMatrix , and @robotman3000

**Comment by DefinitlyEvil** [comment]
Stop arguing and turn to @CloudLandGame , there we can fully customize anything we want.

**Comment by TheDiamondYT1** [comment]
No. @DefinitlyEvil. The game looks promising, but DragonProxy is nothing to do with that. People want DragonProxy and one day when JDK 9 stops being a ****, i will give them it.

**Comment by DefinitlyEvil** [comment]
@TheDiamondYT1 ya ur right tho

**Comment by Shiny-andKittens** [comment]
I have an idea: make this a plugin, because plugins are not only easy to code but easy to install as well. I think that if we do that, we could code it like this: 

E.g., block placement

@EventHandler
onBlockPlaceEvent(){
*insert code to send a MCPE packet*
}

**Comment by Shiny-andKittens** [comment]
Oops, I forgot about the mention tag, I'm sorry about that, ignore this.

**Comment by RednedEpic** [comment]
Wait, if you guys haven't seen, there is already a plugin that does this. It is called ProtocolSupportPE (https://github.com/ProtocolSupport/ProtocolSupport/tree/mcpenew). There is no download (meaning you have to compile it yourself), but it seems somewhat active. I tried using it on my server, cross compatibility between normal MCPC versions work (e.g: 1.9 & 1.12 work together), but I haven't seem to have gotten MCPE working. Maybe we could speak with them.

**Comment by TheDiamondYT1** [comment]
DragonProxy is meant to let mcpe join mcpc servers without having to own the PC server. I can't use protocol support pe to join mineplex, can o?

**Comment by Shiny-andKittens** [comment]
So, what say you, @DefinitelyEvil ?

**Comment by TekkitCommando** [comment]
I will say this, and I think I speak the same as DefinitlyEvil. This project will never get finished if it keeps getting completely deleted and everyone keeps asking "what do we do". Def and I left to other things like Cloudland and KraveTech (or KraveIO) and we pretty much left Luke to make the decisions as the new main maintainer of the project. DefinitlyEvil and I are no longer actively working on this project. We watch it still but mostly because we have a hope that Luke will set a project plan and get this going. You guys have two options really that will get you user support and that is either delete DragonProxy completely and work on the original Dragonet plan or focus exclusively on DragonProxy and start with handshake, protocol and json messages and make and get milestones going to track progress of the features you need. This project won't get anywhere with everyone looking for someone else to get this kicked off. Someone make a roadmap and just get the first connection working and go from there.

**Comment by TheDiamondYT1** [comment]
Since I only really have access to an Android, I'm waiting for JDK 9 to become more stable (as JDK 8 is not available on Android), and then I will work on DragonProxy. I don't think Dragonet is a good idea at the moment, as it's such a large project. I'll code DragonProxy from scratch so I actually *understand* the code (I never understood the old code) and I have a much better understanding of the protocol now. For anyone wondering what extra features I'll add:

* Translations and configurable messages
* Configuration files
* Xbox live forcing and authentication
...and more

That's only a short list of things I can thing of right now. I'm sorry for constantly deleting and re-creating the repo, I have OCD and like to start fresh. One day this project will become great again and we can enjoy Hypixel on our mobile devices 

I'd like to thank a few people:
<br>
**Tobias (@DefinitelyEvil)**  
For creating this awesome project. Believe it or not it used to work, and I could play Factions on TheArchon on my Android device. 
<br>
**Ethan (@TekkitCommando)**  
Hosting the website. Motivation. Probably some developmebt. Im not quite sure what you actually did xD
<br>
**@MrPowerGamerBR**  
Hosting a test server, contributing code, believing in the project before it started getting inactive. Thank you.

Give it a while, and you'll see some commits pop up on your dashboard. But, untill then, don't bother making any pull requests. I'll reject them. You can contact me on [Twitter](https://twitter.com/TheDiamondYT) if you need me, or just reply to this issue.

**Comment by Shiny-andKittens** [comment]
I know this sounds like a kinda crazy idea, but what if we ask mojang to help? Dinnerbone (not using mention tags yet) help make a lot of stuff involving servers, in fact, that's how he was even hired by Mojang in the first place.

**Comment by Shiny-andKittens** [comment]
And, by the way, having OCD is fine, I have ADHD and if I were more important to the project I probably would have done the same thing.

**Comment by coolnickname** [comment]
If Mojang wanted PC <-> PE compatibility they would just have used the same protocol.

**Comment by TekkitCommando** [comment]
Plus mojang are greedy bastards now a days and dinnerbone doesn't work on Minecraft anymore.

**Comment by TheDiamondYT1** [comment]
Not Mojang, Microsoft

**Comment by TheDiamondYT1** [comment]
Notch owns a multi million dollar house in beverly hills and Mojang are needing to steal peoples money to avoid becoming broke

**Comment by Shiny-andKittens** [comment]
Unsubscribed. Not gonna listen if nobody wants to fix it anymore

**Comment by DaMatrix** [comment]
pepsiproxy is an option for The Future (tm)

**Comment by TheDiamondYT1** [comment]
@Shiny-andKittens Didn't you read my long post?

**Comment by MrPowerGamerBR** [comment]
I think ProtocolSupportPE is a better idea and overall a better project.

And I think Dragonet was a more doable project than DragonProxy. (And I was developing a similar idea: Glowstone with PE support... and I even got far as getting the client to walk around in the world (yes, I figured out how to send chunks myself) and view players/mobs/etc... stopped it due to PSPE)

**Comment by TheDiamondYT1** [comment]
@MrPowerGamerBR But With PSPE you cant join PC servers that you dont have the plugin installed

**Comment by MrPowerGamerBR** [comment]
@TheDiamondYT1 yeah, but do I care about that? Absolutely not.

I wanted to use DragonProxy connected to my own PC server so I could use a good server software (Spigot) instead of relying on other PE server softwares.

So I don't care if I need to install a plugin (like ProtocolSupportPE), I just want a way to have a good PE software. (which couldn't be done with only DragonProxy)

**Comment by TheDiamondYT1** [comment]
I think the point of DragonProxy is to allow MCPE clients to connect to *any* MCPC server. It could be implenented as a plugin to a MCPE server software, but theres no good ones except PocketMine which is PHP — need i say more?

**Comment by TekkitCommando** [comment]
No it would be a plugin for MCPC not MCPE server. Also Pocketmine sounds like the worst idea ever. A server software written PHP? Um no thank you.

**Comment by DefinitlyEvil** [comment]
The point I made this is to benefit players not server owners btw.
