### ISSUE TITLE
Some blocks are "update blocks"

### ISSUE THREAD

**Issue by TheGameratorT** [DragonetMC/DragonProxy#106]
Some of the blocks are grass saying please update, I think this can help with the in time chunck conversion, or just the list of IDs on Java to Bedrock: https://www.planetminecraft.com/mod/anvil-to-leveldb-converter-java-to-pocket-edition/

**Comment by DefinitlyEvil** [comment]
Will check it out, thx

**Comment by HoverEpic** [comment]
Fixed in future release \o/

PC view :
![image](https://user-images.githubusercontent.com/3588249/33807489-f27537f8-ddd7-11e7-8a97-1ec358b7613d.png)

Bedrock view :
![image](https://user-images.githubusercontent.com/3588249/33807477-d499f8ea-ddd7-11e7-8788-969e92c73410.png)

All blocs have bad metadata, facing and colors doesn't work for now.
Missing : 
- prismarine (block non implemented in Bedrock)
- prismarine_bricks (block non implemented in Bedrock)
- paintings (its an entity)
- beds (need blocks metadata translator)
- items frames (need blocks metadata translator)
- banners (need blocks metadata translator)
- signs (need blocks metadata translator)
- beacons
- heads

**Comment by DefinitlyEvil** [comment]
Cool you built this?

**Comment by HoverEpic** [comment]
nope, it's a 1.12 items testing map

**Comment by DefinitlyEvil** [comment]
@HoverEpic okie xD I thought it would be cool if you made this map :P

**Comment by HoverEpic** [comment]
fixed for most blocks.
