### ISSUE TITLE
movement on slabs/staircases/half-blocks

### ISSUE THREAD

**Issue by DefinitlyEvil** [DragonetMC/DragonProxy#164]
MCBE behaves kinda different than MCJE does, so I think we can use some regulator thingy to fix this. 
like: 
`if 0.1 > ~y < 0.25, changed to fixed 0.25`
just an example

**Comment by maxencehenneron** [comment]
I was looking at this particular issue, is there a way to know if the user is on such surfaces?

**Comment by HoverEpic** [comment]
Nope, we probably need a map cache to know this.

**Comment by maxencehenneron** [comment]
The problem is that there is a server side correction of the user position (along with a message "The player moved wrongly") so we would need a way to change the position of the user when translating the packet so the server doesn't flag the movement as suspicious. That's mainly because the java and C++ versions of Minecraft use different physic engines

I think I just fixed the issue with one line of code edit: nevermind, it's harder than I think, but I made a good discovery;

**Comment by dernise** [comment]
I think I just fixed the issue with one line of code

**Comment by maxencehenneron** [comment]
Do you guys have a discord / slack or IRC channel? it would be easier to communicate on findings for such projects

**Comment by DefinitlyEvil** [comment]
this will be silly to cache the map, just check all the Y value in each single MovePlayerPacket! ;) 
if players TPed back, just send a fix packet by lifting the player up from its old position and send the normal one.

**Comment by maxencehenneron** [comment]
Right, or we could only cache the stairs/slabs, I'm currently looking at the source code and it's quite harder that just modifying the Y value, because there is a velocity check and apparently the player goes too fast in stairs when using the bedrock edition, I'm currently adding logs to the net.minecraft.server to see what's going on

**Comment by maxencehenneron** [comment]
If the player is TPed back, it breaks the movement so each step would freeze the user for some seconds, and I'm not sure how to deal with this

**Comment by ApocalypsjeNL** [comment]
@dernise yes we have discord, https://discord.gg/grFtgfZ

**Comment by maxencehenneron** [comment]
#197 fixes the issue for stairs. Will add slabs after it is merged. Can someone gather a list of all half-blocks?

**Comment by DefinitlyEvil** [comment]
@dernise stairs/slabs and... ummm....... afaik that's all???????

**Comment by ApocalypsjeNL** [comment]
Slabs, fence, fence gate inside a cauldron
