### ISSUE TITLE
{New Way of using} [DragonProxy]

### ISSUE THREAD

**Issue by jbreadtoasted** [DragonetMC/DragonProxy#213]
Hello, I am here with an idea on using [dragonproxy]. When making a server, I would like to be able to just run the [dragonproxy.jar] as its own but have the bukkit api implemented with the latest version still allowing the lates version of minecraft windows 10 edition and pocket edition to connect. Now in theory this would work. However im not sure how you would acheive this. I personally dont have enough money to purchase 2 dedicated hosts and my internet provider does not allow me to open my ports for port forwarding. Now when running [dragonproxy.jar] as our server like so 
[02:10:36 INFO]: This server is running CraftBukkit version git-Bukkit-bd30843 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT). Because its already running this bukkit version when running the [dragonproxy.jar] directly as the server jar. Thus allowing pc, windows10 edition, and pocket editions to connect while allowing us to still utilize bukkits plugin easily. I hope this is not to complicated and if you have further questions about what i am talking about please message my discord. **jbreadtoasted#4918**

**Comment by TheMasterBlaster** [comment]
So if I understand your talking about turning DragonProxy into just a normal Server supporting MC PE/PC clients? If that is correct that would require a full re code and would change the whole point of using dragonproxy. If I misunderstood i apologies.

**Comment by HoverEpic** [comment]
We do not plan to implements DragonProxy as a plugin or a server for now, it will be a huge work.

**Comment by jbreadtoasted** [comment]
Ok well then i have another problem i am currently having issues getting my DragonProxy to even work i have setup a craftbukkit server and the dragonproxy in the way i think it would work but i have a link to the video. https://www.youtube.com/watch?v=NpVFhIKnkis
Please skip ahead a little bit if you feel like i made the video raw so.. But yeah i really need help

**Comment by jbreadtoasted** [comment]
I need a full explination on how to set it up so i can create a video for everyone to be able to get this to work. There is literally nowhere showing us how to set it up properly and i want to share with the world on how to get it working right!

**Comment by TheMasterBlaster** [comment]
Looks like your telling dragon proxy to bind to the port 25565 DragonProxy needs to be on a different port then the server your connecting it to. Sorry if I got this incorrect I'm currently at work.

**Comment by HoverEpic** [comment]
I'll try to explain how to setup Dragonproxy, and if it works, i'll update the howto setup.

1. setup spigot or bungeecord network for your need (or a classic minecraft server)
2. Test your server with a 1.12.2 client (important to proov that you can connect with the good version)
3. setup DragonProxy (download the release latest jar, start ont time, then stop the process)
`java -jar DragonProxy-x.x.jar` then Ctrl+C
4. in the config, modify :
```yaml
remote_servers:
  my_pc_server:
     remote_addr: '127.0.0.1'
     remote_port: 25565
```

Optional : configure online or offline mode, configure XBoxLive auth (possibly cracked clients)
127.0.0.1 as target minecraft server, 25565 as the target port
5. start DragonProxy, then start your W10 minecraft (or tablet, or other bedrock client), then add your computer IP to the server list.
IF you are on W10 and the proxy is on the same machine, it should NOT works, because microsoft block minecraft Bedrock on localhost, but there is always a solution, use http://pmmp.readthedocs.io/en/rtfd/faq/connecting/win10localhostcantconnect.html
6. enjoy

Hope it will work on your computer. For other people with problems with hosters, we do not provide support for this types of setup.

**Comment by TheMasterBlaster** [comment]
If been looking around online it seems a lot of people think DragonProxy is a plugin for spigot or Bungee cord xD Might be some of the issue with some people lol.

**Comment by DefinitlyEvil** [comment]
@TheMasterBlaster those ppl are stupid lol they don't read

**Comment by lukeeey** [comment]
i updated the repo description

**Comment by HoverEpic** [comment]
lol, you are so hard!

**Comment by jbreadtoasted** [comment]
Hey anyone willing to show me how the DragonProxy works code wise so i can maybe help in advancing and improving it? I have my own github i just need to learn how different things are called like player movement interactions etc so we can get items and such to be able to be used withought throwing out errors

**Comment by HoverEpic** [comment]
it's not easy, but i can try.
For the most part, things are handled in translators, PC packet to PE packet and PE packet to PC packet.
But, have you been able to get the proxy working? because if you cannot setup it, it will be hard to test ^^

**Comment by yannicklamprecht** [comment]
The Bedrock Edition Loopback stuff is informative. I guess that was the reason I stopped testing pocket mine MP or a derivative of it.
