### ISSUE TITLE
World doesn't load

### ISSUE THREAD

**Issue by Akiyama0** [DragonetMC/DragonProxy#220]
My server can't run PE normally, and PE enters the empty and continuous flicker.
Unable to load, PE can't see the chat interface and content, but the server side can see that the Java side does not return the data to the dragon end.

**Comment by Akiyama0** [comment]
It's always a void，no data is returned

**Comment by Akiyama0** [comment]
There is an entity, but the map is not loaded.

**Comment by DefinitlyEvil** [comment]
use the latest

**Comment by Akiyama0** [comment]
It's the latest version

**Comment by DefinitlyEvil** [comment]
please describe more so we can help

**Comment by HoverEpic** [comment]
Probably the empty world bug, sometimes the player spawn in an empty world, sometimes the player spawn in a block, we have to fix this problem.

**Comment by Akiyama0** [comment]
thanks

**Comment by Akiyama0** [comment]
Some maps will be loaded but some blocks are still not loaded.

**Comment by Akiyama0** [comment]
Sometimes there is no normal link server.

**Comment by Akiyama0** [comment]
Some blocks are free of luminance and into the empty area, similar to the void but the physical display.

**Comment by Akiyama0** [comment]
This is my question report, please read it.

**Comment by HoverEpic** [comment]
Luminance is not handled. For the empty world bug, i'm still on it, it's not stable any more...

**Comment by HoverEpic** [comment]
Should be ok, tell me if the problem is still appening.

**Comment by Jocke155** [comment]
World still doesn't load sometimes when teleporting or changing world. 

I've noticed that changing the render distance back and forth can help sometimes.

**Comment by HoverEpic** [comment]
Using lastest master? Online or offline mode? I have worked on that yesterday, tell me what build you use (version in beginig of the log).

**Comment by RobertSzujo** [comment]
Sadly long-range teleportation (outside of view distance) or changing world still doesn't work. After teleporting, the map won't load around you (but it looks like entities like armor stands can actually load). If you want to let the map load, you have to teleport, then disconnect & reconnect. Walking around (without teleporting) works fine, the chunks can load in this case. I'm using Paper as server software (fork of Spigot) and the latest Jenkins snapshot of DragonProxy (Build 54). I tried DragonProxy with normal Spigot (instead of Paper) a week ago, it also didn't work well, but sometimes it could actually load the map around you (it happened totally random, couldn't find what caused it to work sometimes). Using earlier builds (around a month ago) worked a bit better, because it could load the map around you if you teleport between worlds, but not if you teleport somewhere in the same world.

**Comment by HoverEpic** [comment]
Don't know whats wrong, but i will work on that again again again again again again again again again again (i'm going to be crazy about this). I think i'm close from the solution.

**Comment by DefinitlyEvil** [comment]
#blame-mojang ;)
