### ISSUE TITLE
Protocol encryption

### ISSUE THREAD

**Issue by HoverEpic** [DragonetMC/DragonProxy#222]
Someone on Discord report that we do not encrypt protocol, that can be a problem.

**Comment by lukeeey** [comment]
Why do you always say protocole and not protocol

**Comment by HoverEpic** [comment]
Because
https://fr.wikipedia.org/wiki/Protocole
https://www.sttmedia.com/characterfrequency-french

**Comment by ghost** [comment]
I'd suggest taking a look at [my implementation](https://github.com/JungleTree/JungleTree/tree/master/service-ccmcb/src/main/java/org/jungletree/service/ccmcb/net/crypto) if you're interested in adding this. It's based on [GoMint](https://github.com/GoMint/GoMint). The community documentation isn't brilliant. There has been some work done, though may be a little outdated.

You will also need to validate the Xbox Live JWT tokens. You won't need the Xbox Live API in order to do this, a standard JWT library will be fine.

https://confluence.yawk.at/display/PEPROTOCOL/Encryption

**Comment by johnnywoof** [comment]
This was already implemented.
https://github.com/DragonetMC/DragonProxy/pull/173

**Comment by HoverEpic** [comment]
I wasn't talking about logging in =)
I'm thinking about server encryption, actualy, the protocol can be listen by a udp proxy, and easyly decoded, @sgdc3 talk me about a possible encryption.
I know DragonProxy is not realy stable now, so i will just close this issue and think about that later.
