### ISSUE TITLE
DragonProxy is back!

### ISSUE THREAD

**Issue by TheDiamondYT1** [DragonetMC/DragonProxy#34]
*"The proxy, the myth, the legend. It's back."*

---

### Yes, it really is back
Luckily for us @robotman3000 has forked the repository and has been working to update the software. Because of this i have done a little repo cleanup for when he decides to merge his changes. 

**I have marked all issues before the refactor with the label "Old"**

If you have any questions or suggestions, please don't hesitate to ask.

**Comment by Lord-Felidae** [comment]
YAAAAY (also: where can I download?)

**Comment by TheDiamondYT1** [comment]
@CubeFromSpace Nowhere atm. Check back when @robotman3000 makes a PR for his changes.

**Comment by wilsondc15** [comment]
YEEEEESSSSSS!!! @robotman3000 you will be a hero if you make this work!

**Comment by robotman3000** [comment]
I'm almost done with the current set of changes I'm working on, and I plan to push them to my fork soon. I have been busy implementing a new networking system that uses a more streamlined data flow. I hope to document the system on the wiki soon

**Comment by Lord-Felidae** [comment]
FINALLY I CAN PLAY BITQUEST ANYWHERE :D 
Wonderful job! I thought Dragonet was dead!

**Comment by DefinitlyEvil** [comment]
sorry to you all guys for I am kinda abandoned this project :( I am rly tired debugging my crappy code and protocol stuff

**Comment by TheDiamondYT1** [comment]
Haha but its gonna make a come back

**Comment by DefinitlyEvil** [comment]
Hopefully that dood will survive from my crappy code (logic errors, memory leaks, runtime exceptions, blah blah blah)

**Comment by inxomnyaa** [comment]
Current issues?

**Comment by MrPowerGamerBR** [comment]
@thebigsmileXD everything doesn't work!

**Comment by inxomnyaa** [comment]
So, its not back.

**Comment by robotman3000** [comment]
@thebigsmileXD It's sorta kinda back. I've pushed a very not working version of the new networking system (Not really tested) in commit daeedc2084ca3afcd99ae7934f141ee370fb037b. The new networking classes are in org.dragonet.proxy.network.adapter. UpstreamSession has become ClientConnection, and the networking part of UpstreamSession and DownstreamSession has been moved into the client and server protocol adapters. DownstreamSession has ceased to exist. The PE networking system no longer uses Nukkit in favor of JRakNet and has been rewritten. @MrPowerGamerBR The translator system should be as you remember it. As it turns out, I didn't need to change it to put in the new network system

**Comment by robotman3000** [comment]
The proxy is now in need of packet classes for the PE networking system. I think we can use sel-project/sel-utils to get these classes either by hand, code generation from the json protocol docs, or using the existing java classes by making a fork and modifying them as needed.

**Comment by robotman3000** [comment]
@DefinitlyEvil I've survived your messy code. I actually really like the translator system design

**Comment by robotman3000** [comment]
@DefinitlyEvil @TheDiamondYT1 Should I go ahead and merge my fork into maser?

**Comment by TheDiamondYT1** [comment]
@robotman3000 No, merge it into branch refactor.

**Comment by inxomnyaa** [comment]
@robotman3000 Sounds good. About PE Packets etc: http://github.com/ClearSkyTeam/PocketMine-MP/tree/cs-1.0 is so far the most vanilla core. Its based on PMMP which is being rewritten by dktapps, but has most of the missing blocks and items in it yet. If you can read basic php code, src/pocketmine/network/packets is the way to go

**Comment by MrPowerGamerBR** [comment]
@thebigsmileXD packets are easy, except...

FullChunkDataPacket.

The issue with DragonProxy is that there isn't a "world" (the client logs in on void), so it becomes very very very difficult to do anything else since there isn't a world to... well, interact, so finishing other translators (example: spawn mob, etc) is impossible because... well, you get the idea.

I already tried a bunch of times to send a chunk data to client, but I always failed, so, if you know how to send it, please tell us ;)

(And don't say to look on PM-MP's packet docs, I already seen that, VarInt X, VarInt Z, byte[] payload, the problem is the "payload" contents)

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR maybe parts are prefixed by some length field?

**Comment by DefinitlyEvil** [comment]
@robotman3000 Thanks xD

**Comment by ghost** [comment]
how to use :(((

**Comment by Pet0203** [comment]
@kaliiksPro Read the comments please, it clearly says the project isn't finished yet. If you want to use it without chunks loading, then go ahead and just compile the code with your favorite IDE.

**Comment by ghost** [comment]
Thx i cant compile:( can anyone help?
I tried to compile but it dont work for me

**Comment by Pet0203** [comment]
@kaliiksPro Did you even read my comment? I said chunks aren't loading = You can't load the world = You can't build, or see anything, it's just white.

**Comment by ghost** [comment]
When developers fix it give they .jar download ?

**Comment by robotman3000** [comment]
@kaliiksPro Yes, when the project is restored to a working state there will be jar downloads provided. At this time the code in my fork at robotman3000/DragonProxy is only able to forward packets between a PC client and a PC server. The transfer modes PC->PE, PE->PC, and PE->PE are still unfinished and not working.

**Comment by MrPowerGamerBR** [comment]
@robotman3000 PE -> PE is easy and probably not even needed anymore since
1.0.3.0 (TransferPacket)

I would help, but I'm busy with my Nukkit fork for my upcoming server.

Em 4 de fev de 2017 13:28, "robotman3000" <notifications@github.com>
escreveu:

@kaliiksPro <https://github.com/kaliiksPro> Yes, when the project is
restored to a working state there will be jar downloads provided. At this
time the code in my fork at robotman3000/DragonProxy is only able to
forward packets between a PC client and a PC server. The transfer modes
PC->PE, PE->PC, and PE->PE are still unfinished and not working.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/DragonetMC/DragonProxy/issues/34#issuecomment-277453022>,
or mute the thread

**Comment by robotman3000** [comment]
@kaliiksPro The following compile instructions assume an ability to use git and maven on whatever platform you use (IE. Linux or Windows). I use Linux so if you are on Windows I won't be of much help.
1. Clone the git repository [https://github.com/robotman3000/DragonProxy.git](https://github.com/robotman3000/DragonProxy.git)
2. Go into the DragonProxy folder that was just downloaded. In that folder there should be 2 folders, DragonProxy and JRakNet along with a file named pom.xml.
3. Run maven with the goal "package"

The compiled jar should be in DragonProxy/DragonProxy/src/target or something like that. You are looking for the "target" folder because that is where maven puts the packaged jars

**Comment by robotman3000** [comment]
@MrPowerGamerBR What exactly does the transfer packet do?

**Comment by MrPowerGamerBR** [comment]
@robotman3000 transfers a player to another server  (the client auto disconnects and reconnects to the new server)

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR But PE -> PE proxy is still needed in server networks, eg. global chat.

**Comment by MrPowerGamerBR** [comment]
@DefinitlyEvil better setting up a socket server instead of passing thru every connection via something like Bungee

**Comment by DefinitlyEvil** [comment]
@MrPowerGamerBR but it still somehow benifits, well anyways

**Comment by Lord-Felidae** [comment]
Is it download ready yet?

**Comment by DaMatrix** [comment]
No, nothing has happened here in the last month or so. DragonProxy is Impossible, have a look at ProtocolSupport.
