### ISSUE TITLE
The proxy crashes minecraft windows 10 edition

### ISSUE THREAD

**Issue by tonibm19** [DragonetMC/DragonProxy#47]
I wanted to try the proxy but it seems minecraft windows 10 will crash with the proxy running.
And if you run mc before the proxy the proxy starts and then inmediately stops.

**Comment by DefinitlyEvil** [comment]
Using the latest snapshot from CircleCI?

**Comment by TheMasterBlaster** [comment]
@tonibm19 @DefinitlyEvil  If you are hosting the Proxy from home you have to change the port the Proxy is trying to bind to. Minecraft Windows 10 Edition will crash when it can not bind to its default port. I hope this helps and have a great day! :)

**Comment by jlirochon** [comment]
Oh ! You are trying to run the proxy and the game on the same computer. I think this is not an expected use case.

Technically it's not impossible to bind 2 servers on the same UDP port, but both have to set the SO_REUSEPORT option when binding. Since we have no control on the game itself, it seems we can't do that.

You can try to set an alternative port for the proxy, for example 19133. Auto-discover may stop working, but you can still add the proxy manually in the game as you would do for a classic MCPE server.

**Comment by tonibm19** [comment]
It worked now having the proxy in a different port.
Still, it doesnt seem to work, but probably is something related to ports.
