### ISSUE TITLE
Agressive behaviour to other projects

### ISSUE THREAD

**Issue by Heath123** [DragonetMC/DragonProxy#474]
Multiple people have been banned from the Discord server for trying to help people by mentioning other projects. GitHub isn't yhe best place to put this but I'm banned now and people will see it here.

**Comment by jehendeoff** [comment]
Well you dm him, I can understand him, and it was like : use it, it's just better. you weren't even telling him like : hey that thing exist, maybe it can help you 

to me you deserved to be ban

and you didn't event tell him that it could help, you just told : use it, it's better, your's just crap, delete it

**Comment by Heath123** [comment]
It is better? I don't see why I can't say that. I took time to help people, and this happens. Most people thank me.

**Comment by lukeeey** [comment]
This action was taken as it is against the rules of the Discord to advertise. I will let it go sometimes, especially if its something completely unrelated. 

Messaging someone who is in my Discord asking telling them to use an alternative software is not good for me. Should i go to the Geyser Discord and advertise DragonProxy? I don't think so. Direct Message advertising is worth a ban on most Discord servers, so i don't see why mine should be any different.

Also, the rules mention no advertising but they will be updated to specifically mention DM advertising as well.

If you are done i will unban you, otherwise have a good day.

**Comment by Meaxis** [comment]
You DM'd me without my consent and thinking I "needed help" where I never complained once about DragonProxy. I then reported you to admins. As said here (https://www.reddit.com/r/discordapp/comments/7j3x2s/psa_sending_invites_to_random_people_breaks_the/), advertising is disallowed. And this is advertising. You are the aggressive one here.

**Comment by Heath123** [comment]
> You DM'd me without my consent and thinking I "needed help" where I never complained once about DragonProxy. I then reported you to admins. As said here (https://www.reddit.com/r/discordapp/comments/7j3x2s/psa_sending_invites_to_random_people_breaks_the/), advertising is disallowed. And this is advertising. You are the aggressive one here.

I was trying to give you support. It wasn't marketing, and it wasn't unsolicited.

**Comment by lukeeey** [comment]
![C42769F1-68EA-459D-AE77-15887265E943](https://user-images.githubusercontent.com/32024335/78459735-f2eb8900-76b2-11ea-9a7c-0073126f0c1f.jpeg)

**Comment by Meaxis** [comment]
Support? For what? 
> It wasn't unsolicited.
Ok Google, define unsolicited
![image](https://user-images.githubusercontent.com/37759268/78459748-6abdb180-76bb-11ea-826f-24b702ffb835.png)
